version: '3'
services:
  ### Posgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: ricardo
      POSTGRES_PASSWORD: testDb123
    ports:
      - "5431:5431"
    expose:
      - 5431
    command: -p 5431

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: ricardo
      MYSQL_PASSWORD: testDb123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306

  ### Posgres database for Products
  db-products:
    container_name: db-products
    image: postgres:16.1
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: ricardo
      POSTGRES_PASSWORD: testDb123
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: -p 5432

  ### Postgres database for keycloack
  db-keycloak:
    image: postgres:16.1
    container_name: db-keycloak
    environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: ricardo
        POSTGRES_PASSWORD: testDb123
    ports:
      - "5433:5433"
    expose:
      - 5433
    command: -p 5432

  # Keycloack configuration
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.4
    command: [ "start-dev" ]
    ports:
      - "8181:8181"
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: ricardo
      DB_PASSWORD: testDb123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181

  ### Zookeeper
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ### Kafka
  ### Kafka
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
